### ISSUE TITLE
Replacement for itmdump

### ISSUE THREAD

**Issue by grigorig** [rtic-scope/itm#13]
The `itm-decode` utility is not a replacement for `itmdump`. Is anything planned in this regard? Something suitable for the common use case of watching SWV debug output live.

**Comment by tmplt** [comment]
> Is anything planned in this regard?

It's  likely in scope, but I cannot find the repository of `itmdump` to compare feature sets. Do you know where it is located?

> Something suitable for the common use case of watching SWV debug output live.

If the SWV is available as a serial device it can be monitored live with `itm-decode --singles /path/to/serial-device`. If `--itm-freq` is specified `itm-decode` configures the device for the given baud rate.

**Comment by grigorig** [comment]
See https://github.com/rust-embedded/itm. It actually says "This crate is now deprecated, please refer to [rtic-scope/itm](https://github.com/rtic-scope/itm) instead.", so I wonder why you don't know about it.

**Comment by tmplt** [comment]
rust-embedded/itm does not contain an `itmdump`, see https://github.com/rust-embedded/itm/issues/33. The issue points to https://github.com/japaric/itm-tools, but that repo does not contain it either. `itm-tools` does contain an `itm-decode` also, but that tool is superseded by this repo's `itm-decode` which offer some additional features.

**Comment by ryan-summers** [comment]
For future reference, itmdump was included in the last release (0.3.1) of itm, but appears to have been removed on master before this was transferred. See https://github.com/rust-embedded/itm/blob/v0.3.1/src/bin/itmdump.rs

**Comment by tmplt** [comment]
Thanks, @ryan-summers.

It seems that `itmdump` is used to decode and print out the payloads of instrumentation packets. While this crate does decode them, `itm-decode` does not currently decode the payload data into strings like `itmdump` seems to do. Closing in favour of #5.
