### ISSUE TITLE
remove the fork info

### ISSUE THREAD

**Issue by jordens** [rtic-scope/itm#19]
The fork markings and the info about this behing "behind rust-embedded:master" is confusing, especially since this repo here is now the main target, and not the fork anymore. Can we remove the fork link?

```
forked from https://github.com/rust-embedded/itm
This branch is 161 commits ahead, 2 commits behind rust-embedded:master.
```

**Comment by tmplt** [comment]
I have filed a request with GitHub to extract the fork as the root of a new fork network. Thanks for pointing it out.
